# Generated by Django 4.2.3 on 2023-07-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
