# Generated by Django 4.2.3 on 2023-07-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_discription_taskmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'description', 'verbose_name_plural': 'descriptions'},
        ),
    ]
