# Generated by Django 4.2.3 on 2023-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='dueDate',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
